services:
  monga:
    image: lorthe/discord-mongaboss:latest
    container_name: mongaboss
    env_file:
      - .env
    environment:
      - MONGABOSS_DISCORD_TOKEN=${MONGABOSS_DISCORD_TOKEN}
      - MONGABOSS_DISCORD_CLIENT_ID=${MONGABOSS_DISCORD_CLIENT_ID}
      - MONGABOSS_DISCORD_SERVER=${MONGABOSS_DISCORD_SERVER}
      - MONGABOSS_LOG_CHANNEL_ID=${MONGABOSS_LOG_CHANNEL_ID}
      - MONGABOSS_ROLE_MONGA_NAME=${MONGABOSS_ROLE_MONGA_NAME}
      - MONGABOSS_ROLE_ADMIN=${MONGABOSS_ROLE_ADMIN}
      - MONGABOSS_TIME_ROLE=${MONGABOSS_TIME_ROLE}
      - MONGABOSS_DEPLOY_COMMANDS=${MONGABOSS_DEPLOY_COMMANDS}
    restart: unless-stopped
